name: Events
on:
    push:
        branches: 
            - "feature/*"
            - master
            - "feature/**"
            - "!feature/featA"  #exclude this branch
        #branches-ignore:
        #    - develop
        #tags:
        #    - v1.*
        #    - "!v1.1"
        #paths:
        #    - "*.js"
    pull_request:
        branches: [master, feature/*]
        types: [opened, assigned]
    issues:
        types: [opened]
jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: Step
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
