name: Pull Request Comment
on:
    pull_request_target:
        types: [opened]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
        - name: Comment on New PR
          uses: actions/github-script@v7
          with:
            script: |
              github.rest.issues.get({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: 'Thanks for contributing!',
              })
                