name: Status Check functions
on:
    push:
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            #- name: Fail
            #  run: exit 1      ##este es por si queremos que falle y pase al job 2
            - name: Step 1
              run: sleep 20
            - name: Runs on failure
              if: failure()
              run: echo "Runs only on failure"
            - name: Runs on success
              if: success()
              run: echo "Runs only on success"
            - name: Always Runs
              if: always()
              run: echo "Always runs"
            - name: Runs when cancelled
              if: cancelled()
              run: echo "Runs on cancelled"
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo "Job 2"