name: Calling reusable WF
on:
    workflow_dispatch:
        inputs:
            name: 
                description: 'Input description'
                type: string
                default: 'Leo'
                required: false
jobs:
    calling-a-reusable-wf:
        uses: github-actions-Leo/udemy-actions/.github/workflows/reusable.yaml
        with:
            name: ${{ inputs.name }}
        secrets: 
            acess_token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-wf-in-the-same-repository:
        uses: ./.github/workflows/reusable-workflow.yaml
    using-reusable-wf-output:
        needs: calling-a-reusable-wf-in-the-same-repository
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repository.outputs.date }}
