name: Workflow Run
on:
    workflow_run:
        workflows: [Repositoru Events]
        types: [completed]
        branches:
            - master
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was triggered because 'Reposiroty Events' was completed"